"""Create skins table

Revision ID: 70575e6eeaf4
Revises: 
Create Date: 2025-02-02 22:53:28.801563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70575e6eeaf4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),  # Określ długość dla VARCHAR
    sa.Column('skin', sa.LargeBinary(), nullable=True),
    sa.Column('render', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skins_id'), 'skins', ['id'], unique=False)
    op.create_index(op.f('ix_skins_name'), 'skins', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skins_name'), table_name='skins')
    op.drop_index(op.f('ix_skins_id'), table_name='skins')
    op.drop_table('skins')
    # ### end Alembic commands ###